Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.hostname = "jenkins"
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.0.7"
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    end
end